/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 05/31/2016
 */
package io.apimatic.examples.http.request;

/**
 * HTTP methods enumeration
 */
public enum HttpMethod {
    GET,
    POST,
    PUT,
    PATCH,
    DELETE
}
