/*
 * DigitalNewzealandLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 06/29/2016
 */
package org.digitalnz.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CollectionSearchRecords 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 4982626485018259810L;
    private LinkedHashMap<String, Object> facets;
    private int numResultsRequested;
    private int resultCount;
    private ResultsCollection results;
    private String start;
    /** GETTER
     * the facet result data (if requested). The facets element will contain one facet-field element corresponding to each facet requested. Each facet-field element contains a sorted list of value elements that are made up of a name and num-results element. 
     */
    @JsonGetter("facets")
    public LinkedHashMap<String, Object> getFacets ( ) { 
        return this.facets;
    }
    
    /** SETTER
     * the facet result data (if requested). The facets element will contain one facet-field element corresponding to each facet requested. Each facet-field element contains a sorted list of value elements that are made up of a name and num-results element. 
     */
    @JsonSetter("facets")
    public void setFacets (LinkedHashMap<String, Object> value) { 
        this.facets = value;
        notifyObservers(this.facets);
    }
 
    /** GETTER
     * the value of the num_results parameter sent to the API method
     */
    @JsonGetter("num_results_requested")
    public int getNumResultsRequested ( ) { 
        return this.numResultsRequested;
    }
    
    /** SETTER
     * the value of the num_results parameter sent to the API method
     */
    @JsonSetter("num_results_requested")
    public void setNumResultsRequested (int value) { 
        this.numResultsRequested = value;
        notifyObservers(this.numResultsRequested);
    }
 
    /** GETTER
     * the total number of results matching this search
     */
    @JsonGetter("result_count")
    public int getResultCount ( ) { 
        return this.resultCount;
    }
    
    /** SETTER
     * the total number of results matching this search
     */
    @JsonSetter("result_count")
    public void setResultCount (int value) { 
        this.resultCount = value;
        notifyObservers(this.resultCount);
    }
 
    /** GETTER
     * the search results data. The results element will contain 0 or more result elements
     */
    @JsonGetter("results")
    public ResultsCollection getResults ( ) { 
        return this.results;
    }
    
    /** SETTER
     * the search results data. The results element will contain 0 or more result elements
     */
    @JsonSetter("results")
    public void setResults (ResultsCollection value) { 
        this.results = value;
        notifyObservers(this.results);
    }
 
    /** GETTER
     * the value of the start parameter sent to the API method
     */
    @JsonGetter("start")
    public String getStart ( ) { 
        return this.start;
    }
    
    /** SETTER
     * the value of the start parameter sent to the API method
     */
    @JsonSetter("start")
    public void setStart (String value) { 
        this.start = value;
        notifyObservers(this.start);
    }
 
}
 