/*
 * DigitalNewzealandLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 06/29/2016
 */
package org.digitalnz.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class GetMetadataInput 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5704080950586028508L;
    private String recordId;
    private String fields;
    /** GETTER
     * Record IDs are identified in the metadata_url field of a results set. 23034653 is an example record ID.
     */
    @JsonGetter("record_id")
    public String getRecordId ( ) { 
        return this.recordId;
    }
    
    /** SETTER
     * Record IDs are identified in the metadata_url field of a results set. 23034653 is an example record ID.
     */
    @JsonSetter("record_id")
    public void setRecordId (String value) { 
        this.recordId = value;
        notifyObservers(this.recordId);
    }
 
    /** GETTER
     * A comma separated list of fields or groups of fields to be returned for each record. Possible groups include 'default' and 'verbose'. If no value is specified, then the 'default' field group will be returned.
     */
    @JsonGetter("fields")
    public String getFields ( ) { 
        return this.fields;
    }
    
    /** SETTER
     * A comma separated list of fields or groups of fields to be returned for each record. Possible groups include 'default' and 'verbose'. If no value is specified, then the 'default' field group will be returned.
     */
    @JsonSetter("fields")
    public void setFields (String value) { 
        this.fields = value;
        notifyObservers(this.fields);
    }
 
}
 